name: embracing-enums
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - type: bind
        source: ./
        target: /app
